---

- name: Configuring local jail
  template: >
    src={{ fail2ban_jail_local }}
    dest=/etc/fail2ban/jail.local
    owner=root
    group=root
    mode=0640
  when: fail2ban_jail_local
  notify: restart fail2ban
  tags:
    - system
    - networking
    - fail2ban
    - config
