---

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - fail2ban

- name: Configure service
  service: name=fail2ban state={{ fail2ban_service_state }} enabled={{ fail2ban_service_enabled }}

